Adding StandardActionConvertible back from ReSwift
ReSwift/ReactiveReSwift pull request #4
Opened 2017-01-08 01:38 UTC by jondwillis

This enables serialization for actions and better compatibility with other ReSwift-* libraries.

Specifically, I am trying to create ReactiveReSwift-Router that depends on ReactiveReSwift. This commit gets the other project compiling. More commits may be on the way. Was there any particular reason you removed that stuff?

2017-01-08 01:50 UTC, Qata commented
I removed StandardAction because it's a bit of a messy way to handle serialisation. The plan is to eventually have a ReactiveReSwift-Serialiser, but I've yet to get started on that.

2017-01-08 02:44 UTC, jondwillis commented
I know there won't be a 1:1 tracking between this and the non-Reactive counterparts, and I can appreciate removing things for clarity and simplicity, but for things that are additive, like `StandardAction`, it could be a good idea to add them until you can replace them with better solutions, Reactive or not :)

2017-01-09 09:11 UTC, Qata requested changes
If you add back tests to bring the total project coverage back to 100% then I'll merge these changes while I work on a new serialiser.

2017-01-11 19:41 UTC, jondwillis commented
@Qata done adding the tests back. I don't know how to re-trigger Codecov though.

2017-01-12 05:49 UTC, Qata commented
<img width="600" alt="screen shot 2017-01-12 at 4 48 57 pm" src="https://cloud.githubusercontent.com/assets/1232443/21878538/16386800-d8e7-11e6-88f4-b0f49dd0006d.png">
Much of what you added isn't actually being tested.

2017-01-18 00:44 UTC, jondwillis commented
@Qata I added the missing coverages. The last two from your screenshot were also (trivially) missing from ReSwift.

2017-01-18 00:44 UTC, Qata approved these changes

2017-01-19 05:41 UTC, merged